### ISSUE TITLE
QT Layout Design Refresh

### ISSUE THREAD

**Issue by CaveSpectre11** [ida-pay/idapay-refresh#2]
Placeholder for the work Yuriy has been doing to refresh the design of the wallet

**Comment by kido72** [comment]
Add branch "Design_Refresh" with new styles for light, blue, crownium themes.

**Comment by kido72** [comment]
Add branch "Design_Refresh_icons" with new icons and pictures for themes.

**Comment by CaveSpectre11** [comment]
merged https://github.com/ida-pay/idapay-refresh/pull/11 and https://github.com/ida-pay/idapay-refresh/pull/10
